/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const r_email: typeof import('../utils/validation-rules')['r_email']
  const r_matchingPassword: typeof import('../utils/validation-rules')['r_matchingPassword']
  const r_maxLength: typeof import('../utils/validation-rules')['r_maxLength']
  const r_minLength: typeof import('../utils/validation-rules')['r_minLength']
  const r_noSpecialChar: typeof import('../utils/validation-rules')['r_noSpecialChar']
  const r_numberOnly: typeof import('../utils/validation-rules')['r_numberOnly']
  const r_phoneNumber: typeof import('../utils/validation-rules')['r_phoneNumber']
  const r_required: typeof import('../utils/validation-rules')['r_required']
  const r_strongPassword: typeof import('../utils/validation-rules')['r_strongPassword']
  const r_username: typeof import('../utils/validation-rules')['r_username']
  const useCustomIconComponent: typeof import('../composables/useCustomIcon')['useCustomIconComponent']
  const useDayjs: typeof import('../composables/useDayjs')['useDayjs']
  const useDrawer: typeof import('../composables/useDrawer')['useDrawer']
  const validationRules: typeof import('../utils/validation-rules')['default']
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly r_email: UnwrapRef<typeof import('../utils/validation-rules')['r_email']>
    readonly r_matchingPassword: UnwrapRef<typeof import('../utils/validation-rules')['r_matchingPassword']>
    readonly r_maxLength: UnwrapRef<typeof import('../utils/validation-rules')['r_maxLength']>
    readonly r_minLength: UnwrapRef<typeof import('../utils/validation-rules')['r_minLength']>
    readonly r_noSpecialChar: UnwrapRef<typeof import('../utils/validation-rules')['r_noSpecialChar']>
    readonly r_numberOnly: UnwrapRef<typeof import('../utils/validation-rules')['r_numberOnly']>
    readonly r_phoneNumber: UnwrapRef<typeof import('../utils/validation-rules')['r_phoneNumber']>
    readonly r_required: UnwrapRef<typeof import('../utils/validation-rules')['r_required']>
    readonly r_strongPassword: UnwrapRef<typeof import('../utils/validation-rules')['r_strongPassword']>
    readonly r_username: UnwrapRef<typeof import('../utils/validation-rules')['r_username']>
    readonly useCustomIconComponent: UnwrapRef<typeof import('../composables/useCustomIcon')['useCustomIconComponent']>
    readonly useDayjs: UnwrapRef<typeof import('../composables/useDayjs')['useDayjs']>
    readonly useDrawer: UnwrapRef<typeof import('../composables/useDrawer')['useDrawer']>
    readonly validationRules: UnwrapRef<typeof import('../utils/validation-rules')['default']>
  }
}